---
name: Processor for Forms submission events
on:
  repository_dispatch:
    types:
      - form-data-received
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: process submit data to generate dor
        id: generate-dor
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run : ls
      - run : |
          pwd
          ls -l
          cd ..
          pwd
          ls -l
      - run: |
          cd my-franlin-website
          npm install
      - run: node ./../../scripts/googleSheetHandler.js
      - name: Get the result
        run: echo "The result of processing was ${{
          steps.generate-dor.outputs.processing-result }}"