---
name: Processor for Forms submission events
on:
  repository_dispatch:
    types:
      - form-data-received
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Node packages
        run: npm ci
      - name: process submit data to generate dor
        id: generate-dor
        env:
          GOOGLE_SERVICEACCOUNT_EMAIL : ${{ secrets.SERVICEACCOUNTEMAIL }}
          GOOGLE_SERVICEACCOUNT_PRIMARYKEY : ${{ secrets.SERVICEACCOUNTPRIMARYKEY }}
        run: node ./scripts/googleSheetHandler.js
      - name: Call Generate Dor api
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://68a0-2401-4900-1f27-6896-a4c0-622f-a7c0-5900.ngrok-free.app/generateDor/docx'
          method: 'POST'
          customHeaders: '{ "Content-Type": "application/json"}'
          data: '{"data":${{steps.generate-dor.outputs.processing-result }}}'
          timeout: 20000