---
name: Processor for Forms submission events
on:
  repository_dispatch:
    types:
      - form-data-received
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Node packages
        run: npm ci
      - name: Check event data
        run : |
          echo "header names= ${{ toJson(github.event.client_payload.headerNames) }}"
          echo "range = ${{toJson(github.event.client_payload.range)}}
          echo "spreadsheetId = ${{toJson(github.event.client_payload.sourceLocation)}}
      - name: process submit data to generate dor
        id: generate-dor
        run: node ./scripts/googleSheetHandler.js ${{ toJson(github.event.client_payload.headerNames) }} ${{toJson(github.event.client_payload.range)}} ${{toJson(github.event.client_payload.sourceLocation)}}
      - name: Get the result
        run: echo "The result of processing was ${{
          steps.generate-dor.outputs.processing-result }}"